dev:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - .:/application/:rw
  environment:
    - NODE_ENV=development
    - MARVEL_TS=
    - MARVEL_API_KEY=
    - MARVEL_HASH=
  command: >
    sh -c '
      /docker-scripts/dev.js
      /docker-scripts/set-app-config.js
      npm start
    '
