dev:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - .:/application/:rw
  environment:
    - NODE_ENV=development
  command: >
    sh -c '
      /docker-scripts/dev.js
      npm install --save-dev fetch-mock
      npm start
    '
